"""Added extended profile fields

Revision ID: 4a2a3da52aad
Revises: 1bf99876fe0d
Create Date: 2025-02-17 19:47:27.134328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2a3da52aad'
down_revision = '1bf99876fe0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('successful_trips', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credibility_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credibility_score')
        batch_op.drop_column('successful_trips')
        batch_op.drop_column('interests')
        batch_op.drop_column('bio')
        batch_op.drop_column('city')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
