"""Add acs_id column to users table

Revision ID: a13011e8ba79
Revises: 4fdfea7137db
Create Date: 2025-03-31 22:08:16.801717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13011e8ba79'
down_revision = '4fdfea7137db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acs_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('acs_id')

    # ### end Alembic commands ###
